import axios from 'axios'

export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_RECIPES_BY_NAME = 'GET_RECIPES_BY_NAME';
export const GET_ONE_RECIPE = 'GET_ONE_RECIPE';
export const CREATE_RECIPE = 'CREATE_RECIPE';
export const FILTER_BY_DIET_TYPE = 'FILTER_BY_DIET_TYPE';
export const ORDER_ALPHABETICALLY_ASC = 'ORDER_ALPHABETICALLY_ASC';
export const ORDER_ALPHABETICALLY_DESC = 'ORDER_ALPHABETICALLY_DESC';
export const ORDER_BY_HEALTHYNESS_ASC = 'ORDER_ALPHABETICALLY_ASC';
export const ORDER_BY_HEALTHYNESS_DESC = 'ORDER_BY_HEALTHYNESS_DESC';
export const CLEAR_DETAIL = 'CLEAR_DETAIL';